name: 🚀 Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DREAMHOST_SSH_KEY }}

   - name: Upload via rsync over SSH
  run: |
    mkdir -p ~/.ssh
    echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    rsync -avz --delete --exclude '.git*' ./ \
      "$DREAMHOST_USERNAME@$DREAMHOST_HOST:$DREAMHOST_REMOTE_PATH"