name: Deploy to DreamHost via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via SFTP to DreamHost
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: iad1-shared-b8-23.dreamhost.com
          username: dh_c7z8d3
          password: ${{ secrets.DREAMHOST_PASSWORD }}
          protocol: sftp
          port: 22
          local_dir: .
          remote_dir: /home/dh_c7z8d3
          passive: true
          delete: false